Repository qtile/qtile, pull requests merged in 2020-04, with the labels that each got.

#1604 Add pyxdg widget requirement in LaunchBar docstring
  libqtile/widget/launchbar.py
Labels: docs, widgets

#1606 add red "Press <M-r> to spawn" to default config
  libqtile/resources/default_config.py
Labels: docs

#1605 fix caption
  docs/manual/config/index.rst
  docs/manual/config/without-dm.rst
Labels: bug, docs

#1669 Spawn terminal
  CHANGELOG
  docs/manual/config/index.rst
  libqtile/resources/default_config.py
  libqtile/utils.py
Labels: enhancement

#1526 Custom keyboard display
  CHANGELOG
  libqtile/widget/keyboardlayout.py
Labels: enhancement, widgets

#1690 base.deprecated does not come up in the logs
  libqtile/widget/base.py
  libqtile/widget/image.py
  libqtile/widget/pacman.py
  libqtile/widget/sep.py
  libqtile/widget/spacer.py
Labels: bug

#1698 moved keybinding image generation into sphinx extension
  docs/sphinx_qtile.py
  setup.py
Labels: docs

#1701 run sphinx build from any directory
  Makefile
  docs/sphinx_qtile.py
Labels: bug, docs
