Repository qtile/qtile, pull requests merged in 2020-08, with the labels that each got.

#1820 Adjust Bar margin/Gap size for struts without duplicating windows (#1654, #1810)
  libqtile/bar.py
  libqtile/core/manager.py
  libqtile/window.py
  test/test_manager.py
Labels: bug, in progress

#1872 Added memory percentage from psutil to memory widget
  libqtile/widget/memory.py
Labels: enhancement, widgets

#1871 Clean up logic in Backlight widget
  libqtile/widget/backlight.py
Labels: bug, enhancement, widgets

#1741 #1707: default layouts to columns and max
  libqtile/resources/default_config.py
Labels: layouts, stale
