Repository qtile/qtile, pull requests merged in 2023-07, with the labels that each got.

#3631 feat(volume/widget) select which emojis show up
  libqtile/widget/volume.py
Labels: stale

#4292 Fix two bugs in MonadThreeCol
  libqtile/layout/xmonad.py
Labels: Needs maintainer review

#4113 Fix `PangoLayout` error on widget reload
  libqtile/widget/base.py
  test/widgets/test_base.py
  test/widgets/test_chord.py
Labels: widgets

#3409 Another go at implementing z-layers for X11
  CHANGELOG
  docs/manual/config/index.rst
  docs/manual/config/lazy.rst
  libqtile/backend/base.py
  libqtile/backend/x11/core.py
  libqtile/backend/x11/window.py
  libqtile/backend/x11/xcbq.py
  libqtile/bar.py
  libqtile/confreader.py
  libqtile/core/manager.py
  libqtile/group.py
  libqtile/layout/max.py
  libqtile/resources/default_config.py
  test/backend/x11/test_window.py
  test/backend/x11/test_xcore.py
  test/layouts/test_max.py
Labels: priority
