Repository qtile/qtile, pull requests merged in 2023-09, with the labels that each got.

#4429 Add more structure to the GitHub issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Needs maintainer review

#3991 Added support for single_border_width for Columns layout
  CHANGELOG
  libqtile/layout/columns.py
  test/layouts/test_columns.py
Labels: stale

#4044 Added toggle for icon in Cmus widget
  CHANGELOG
  libqtile/widget/cmus.py
Labels: widgets, stale
